repos:
    - repo: https://github.com/rohaquinlop/complexipy-pre-commit
      rev: v5.1.0
      hooks:
          - id: complexipy

    - repo: https://github.com/executablebooks/mdformat
      rev: 1.0.0
      hooks:
          - id: mdformat
            additional_dependencies:
                - mdformat-mkdocs>=0.2.1
            args:
                - --align-semantic-breaks-in-lists
            exclude: |
                (?x)^(
                    CHANGELOG\.md
                )$
