paths = ["."]
max-complexity-allowed = 15
quiet = false
ignore-complexity = false
failed = false
sort = "asc"
exclude = ["tests/**"]
no-ignore = false
report-ignored = false
output-csv = false
output-json = false
