name: Deploy docs

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1
        with:
          python-version: '3.10'
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: uv run mkdocs gh-deploy --force
