[package]
name = "complexipy-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
publish = false

[lib]
name = "complexipy_wasm"
crate-type = ["cdylib", "rlib"]

[dependencies]
complexipy-core = { path = "../complexipy-core", default-features = false, features = ["wasm"] }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
